part1/1.15: Homework/accounts/urls.py
from django.urls import path
from . import views
aap_name = "accounts"
urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('searchpage/',views.SearchResultsView.as_view(), name = 'searchpage'),
    path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

    
    path("doctor/", views.doctor, name="doctor"),
    path("doctorprofile/<int:id>/", views.doctorprofile, name="doctorprofile"),
    path("ambulance/", views.ambulance, name="ambulance"),
    path('product/<int:id>/', views.product, name="product"), 
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("update_item/",views.updateItem, name= "update_item"),
    path("process_order/",views.processOrder, name= "process_order")


]

part1/1.15: Homework/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('',include('accounts.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/',include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
    

]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

part1/1.15: Homework/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.enums import Choices
from django.db.models.fields import DecimalField
# Create your models here.
PRODUCT_CATEGORIES = [('Personal Care', 'Personal Care'), ('Family Care', 'Family Care'),
                      ('Fitness and Suppliments', 'Fitness and Suppliments'), ('Pharmacy', 'Pharmacy')]

SEX = [('Male', 'male'), ('Female', 'female'), ('Other', 'other')]

DOCTOR_CATAGORIES = []

class Doctor(models.Model):
    docname = models.CharField(max_length=50, null=True, blank=True)
    docfield = models.CharField(
        max_length=50, null=True, blank=True)  # specializations
    experience = models.CharField(max_length=50, null=True, blank=True)
    images = models.ImageField(null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    research_journals = models.CharField(max_length=500, null=True, blank=True)
    awards = models.CharField(max_length=500, null=True, blank=True)
    study = models.CharField(max_length=500, null=True, blank=True)
    phone = models.DecimalField(max_digits=10, decimal_places=0, null=True)
    websitelink = models.URLField(max_length=50, null=True)
    email = models.EmailField(max_length=50, null=True)
    facebook = models.URLField(max_length=50, null=True)

    def __str__(self):
        return self.docname + ' ' + str(self.id)

    @property
    def imageURL(self):
        try:
            url = self.images.url
        except:
            url = ''
        return url


class DoctorAppointment (models.Model):
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=30, null=True)
    phone = models.DecimalField(max_digits=10, decimal_places=0, null=True)
    sex = models.CharField(choices=SEX, max_length=6)
    descriptions = models.CharField(max_length=1000, null=True)


    def __str__(self):
        return self.name


class Ambulance (models.Model):
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=30, null=True)
    descriptions = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    # On_delete deletes user if user item is deleted
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=30, null=True)
    phone_number = models.IntegerField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):

    name = models.CharField(max_length=100, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    descriptions = models.CharField(max_length=1000, null=True)
    category = models.CharField(max_length=24, choices=PRODUCT_CATEGORIES)
    smalldescription = models.CharField(max_length=300, null=True)
    images = models.ImageField(null=True, blank=True)
    delivery_date = models.DateTimeField(auto_now_add=True, null=True)
    prescribedmed = models.BooleanField(default=False, null=True, blank=False)

    def __str__(self):
        return self.name + ' ' + str(self.id)

    @property
    def imageURL(self):
        try:
            url = self.images.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    uploadpres = models.ImageField(null=True, blank=True)
    ordered_date = models.DateTimeField(auto_now_add=True, null=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transcation_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def imageURL(self):
        try:
            url = self.images.url
        except:
            url = ''
        return url

    # def __str__(self):
    #     return str(self.customer)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.prescribedmed == False:
                shipping = True
        return shipping


class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL,  blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    # if order gets deleted then also the shipmnet info remains
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL,  blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    province = models.CharField(max_length=50, null=True)
    phonenumber = models.DecimalField(
        max_digits=10, decimal_places=0, null=True)
    added_date = models.DateTimeField(auto_now_add=True, )

    def __str__(self):
        return self.address

part1/1.15: Homework/accounts/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.views.generic import ListView
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sessions.models import Session
from django.views.generic.base import TemplateView
from .forms import AmbulanceForm, NewUserForm, DoctorAppointmentForm
from ecom.settings import EMAIL_HOST_USER
from .models import *
from django.http import JsonResponse
import json
import datetime
from django.contrib.auth.models import Group
# from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user, allowed_users, admin_only
from .util import cookieCart, cartData, guestOrder


@unauthenticated_user
def register_request(request):
    # if request.user.is_authenticated:
    # 	return redirect('home')    pachi loged in  user lai yesma access nadina ho yo
    # else":
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            email = request.POST['email']
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            user = form.save()

            if User.objects.filter(username-username).exists():
                messages.info(request, 'Sorry! Username already taken')
                return redirect('home')

            if len(username) < 10:
                messages.error(
                    request, " Your user name must be under 10 characters")
                return redirect('register')

            if (password1 != password2):
                messages.error(request, " Passwords do not match")
                return redirect('register')

            username = form.cleaned_data.get('username')
            login(request, user)
            messages.info(request, "You are now successfully registered.")
            return render(request, 'accounts/home.html')
    form = NewUserForm
    context = {"register_form": form, 'items': items,
               'order': order, 'cartItems': cartItems, 'shipping': False, }
    return render(request, "accounts/login&register/register.html", context)


@unauthenticated_user
def login_request(request):
    # if request.user.is_authenticated:
    # 	return redirect('home')    pachi loged in  user lai yesma access nadina ho yo
    # else":
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(
                    request, "Welcome, " + username)

                # return render(request, "accounts/home.html")
                return redirect(home)
        else:
            messages.error(request, "Invalid username or password.")

    form = AuthenticationForm()
    context = {'items': items, 'order': order,
               'cartItems': cartItems, 'shipping': False, 'login_form': form}
    return render(request, 'accounts/login&register/login.html', context)


def logout_request(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    logout(request)

    messages.info(request, "You are now sucessfully logged out!!")
    context = {'items': items, 'order': order,
               'cartItems': cartItems, 'shipping': False, }
    return render(request, "accounts/home.html", context)


def password_reset_request(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.txt"
                    cred = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'E-Pharma',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, cred)
                    try:
                        send_mail(subject, email, 'bhatta.abishek11@gmail.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    # return render(request,' password_reset/done/')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    context = {" password_reset_form": password_reset_form, 'items': items,
               'order': order, 'cartItems': cartItems, 'shipping': False, }
    return render(request, "accounts/password/password_reset.html/", context)


# def password_reset_request_de(request):
#     if request.method == "POST":
#         password_reset_form = PasswordResetForm(request.POST)
#         if password_reset_form.is_valid():
#             data = password_reset_form.cleaned_data['email']
#             associated_users = User.objects.filter(Q(email=data))
#             if associated_users.exists():
#                 subject = request.POST.get('subject', 'Password reset')
#                 messages = request.POST.get('message', 'Hey')
#                 recepient = str(sub['Email'].value())
#                 send_mail (subject, messages, EMAIL_HOST_USER, [recepient], fail_silently= False )
#                 return  redirect("/password_reset/done/")
#     password_reset_form = PasswordResetForm()
#     return render(request, "accounts/password/password_reset.html/", context={"password_reset_form": password_reset_form})


def home(request):
    products = Product.objects.all()
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'products': products, 'cartItems': cartItems}
    return render(request, 'accounts/home.html', context)


# @login_required(login_url='login')
def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order,  'cartItems': cartItems}
    return render(request, 'accounts/cart.html', context)


def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order,
               'cartItems': cartItems, 'shipping': False}
    return render(request, 'accounts/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    # get and create cause i need to update if item already exist
    order, created = Order.objects.get_or_create(
        customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse("Item has been added", safe=False)


def processOrder(request):
    transcation_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transcation_id = transcation_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            province=data['shipping']['province'],
            # phonenumber=data['shipping']['phonenumber'],


        )
    return JsonResponse("Process Complete! Item deleivered soon", safe=False)


def product(request, id):
    item = Product.objects.all()
    pro_id = Product.objects.get(id=id)
    data = cartData(request)
    cartItems = data['cartItems']

part1/1.15: Homework/accounts/templates/accounts/ambulance.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}
<!-- Amublance Service -->
<div class="row">
    <div class="column">
        <!-- style="background-color:#aaa; -->
        <div class="centered">
            <img src="{% static 'images/health.PNG'%}"
                alt="Sebium Hydra Ultra Moisturising Compensating Care, BIODERMA , 40ml 1.33 fl. oz.">
        </div>
    </div>
    <div class="column" style="border-left:2px solid #a9a9a9; ;">
        <!-- style="background-color:#bbb; -->
        <p class="head-part ">Are you facing any problem?</p>
        <p> Epharma is here to help you. With our well experience team we promise to deliver quality goods and
            services. For any concern, feel free to talk to us and here are
            <a href="http://nepal.gov.np:8080/NationalPortal/view-page?id=140" target="_blank">Amublance Service list.</a> or,
        </p>


        <form method="POST">
            {% csrf_token %}
            <div class="form-group"></div>
            <input type="text" name="name" maxlength="100" required="" id="id_name" placeholder=" Name"> <br> <br>
            <input type="email" name="email" maxlength="30" required="" id="id_email" placeholder=" E-mail"> <br> <br>

            <textarea name="descriptions" maxlength="1000" required="" id="id_descriptions" class="form-control"
                placeholder="Any Problems!">
            </textarea>
            <br>

            <button class="btn btn-outline-success" type="submit" value="Continue">Success</button>
        </form>
    </div>


</div>
</div>
{% endblock %}

part1/1.15: Homework/accounts/templates/accounts/cart.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}
<!-- Shoping Cart -->
  <!-- Shoping Cart -->

  <div class="row">
    <div class="col-lg-12">
        <div class="box-element">

            <a class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th>
                        <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
                    </th>
                    <th>
                        <h5>Total:<strong> Rs.{{order.get_cart_total}}</strong></h5>    <!-- |floatformat:2 -->
                    </th>
                    <th>
                        <a style="float:right; margin:5px;" class="btn btn-success"
                            href="{% url 'checkout'%}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex:1">
                    <p>Rs.{{item.product.price}}</p>   <!-- |floatformat:2 -->
                </div>
                <div style="flex:1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img  data-product={{item.product.id}}  data-action="add" class="chg-quantity update-cart" src="{% static  'images/2+arrow-down.png' %}">

                        <img data-product={{item.product.id}}  data-action="remove" class="chg-quantity update-cart" src="{% static 'images/3+arrow-up.png'%}">
                    </div>
                </div>
                <div style="flex:1">
                    <p>Rs.{{item.get_total}}</p>   <!-- |floatformat:2 -->
                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock  %}

part1/1.15: Homework/accounts/templates/accounts/checkout.html
{% extends "accounts/main.html" %}
{% load static %}
{% block content %}
<!-- Checkout Cart -->

<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="province" placeholder="State/Province..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="phonenumber" placeholder="Phonenumber ">
                    </div>
                </div>
                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>
        <div class="box-element hidden" id="payment-info">
            <h5>Cash on Delivery</h5>
            <button class="btn btn-success " id="make-payment">Proceed</button> <!-- id="form-button"  -->
        </div>
    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex:1">
                    <p>Rs.{{item.product.price}}</p> <!-- |floatformat:2 -->
                </div>
                <div style="flex:1">
                    <p>x{{item.quantity}}</p>
                </div>
            </div>
            {% endfor %}
            <h5>Items: {{order.get_cart_items}}</h5>
            <h5>Total: Rs.{{order.get_cart_total}}</h5> <!-- |floatformat:2 -->
        </div>
    </div>
</div>
</div>

        <script type="text/javascript">
            var shipping = '{{order.shipping}}'

            var total = '{{order.get_cart_total }}'

            if (shipping == 'False') {
                document.getElementById('shipping-info').innerHTML = "Enter Upload the Prescription"
            }

            if (user != 'AnonymousUser') {
                document.getElementById('user-info').innerText = ''
            }
            if (shipping == 'False' && user != 'AnonymousUser') {
                document.getElementById('form-wrapper').classList.add('hidden')
                document.getElementById('payment-info').classList.remove('hidden')
            }




            var form = document.getElementById('form')

            form.addEventListener('submit', function (e) {
                e.preventDefault()
                // form.addEventListener('submit', function (e) {
                //     e.preventDefault()
                console.log('Form Submitted.....')
                //hide name and email for logged in user
                document.getElementById('form-button').classList.add('hidden')
                //shows payment if logged in and buys not prescribed medicine
                document.getElementById('payment-info').classList.remove('hidden')
            })


            document.getElementById('make-payment').addEventListener('click', function (e) {
                submitFormData()
            })

            function submitFormData() {
                console.log('Payment button clicked')



                document.getElementById('make-payment').addEventListener('click', function (e) {
                    submitForm()
                })
                function submitForm() {
                    console.log("Okay now you can go ahead")
                    var userFormData = {
                        'name': null,
                        'email': null,
                        'total': total,
                    }

                    var shippingInfo = {
                        'address': null,
                        'city': null,
                        'province': null,
                        'zipcode': null,
                    }

                    if (shipping != 'False') {
                        shippingInfo.address = form.address.value
                        shippingInfo.city = form.city.value
                        shippingInfo.province = form.province.value
                        shippingInfo.zipcode = form.zipcode.value
                    }

                    if (user == 'AnonymousUser') {
                        userFormData.name = form.name.value
                        userFormData.email = form.email.value
                    }

                    console.log('Shipping Info:', shippingInfo)
                    console.log('User Info:', userFormData)

                    var url = "/process_order/"

                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Accept': 'application/json',
                            'X-CSRFToken': csrftoken,
                        },
                        body: JSON.stringify({ 'form': userFormData, 'shipping': shippingInfo }),

                    })
                        .then((response) => response.json()) //Convert response to JSON
                        .then((data) => {       //Perform actions with the response data from the view

                            console.log('Success:', data);
                            alert('Transaction completed');

                            cart = {}
                            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

                            window.location.href = "{% url 'home' %}"

                        })
                }
            }
        </script>


        {% endblock %}

part1/1.15: Homework/accounts/templates/accounts/messages.html
{% if messages %}
{% for message in messages %}
<a class="btn btn-info" onclick="toastr.info('{{ message.tags }}');"> {{message}}</a>
{% endfor %}
{% endif%}

part1/1.15: Homework/accounts/templates/accounts/searchpage.html
{% extends 'accounts/main.html'%}
{% load static %}
{% block content %}

<body>
    <!-- <div class="row">
                <div class="col-md-4">
                    <img src="{{result.imageURL}}"  class="img-fluid" alt="">
                </div>
                <br>
                <div class="col-md-8">
                    <h5>{{ result.name }}</h5>
                    <br>
                    <h5>{{result.descriptions}}</h5>
                </div>
            </div> -->
    <div class="products">
        <div class="container">
            <h1 class="lg-title">
                <h3>Search Result for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            </h1>
            <hr>

            <div class="product-items">
                {% for result in results %}
                <!-- single product -->
                <div class="product">
                    <div class="product-content">
                        <div class="product-img">
                            <a href="{% url 'product' result.id %}"><img src="{{ result.imageURL }}"
                                    alt="product image"></a>
                        </div>
                        <div class="product-btns">
                            <button data-product={{result.id}} data-action="add" type="button"
                                class="btn-cart update-cart"> Add to cart
                                <span><i class="fas fa-plus"></i></span>
                            </button>
                            <!-- <button type="button" class="btn-buy"> buy now
                                   <span><i class="fas fa-shopping-cart"></i></span>
                              </button> -->
                        </div>
                    </div>
                    <div class="product-info">

                        <a href="{% url 'product' result.id %}" class="product-name">{{result.name}}</a>
                        <p class="product-price">Rs.{{result.price}}</p> 
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</body>
{% endblock %}